### ISSUE TITLE
Release version 2.0.0

### ISSUE THREAD

**Issue by Hinyka** [hallme/woo-address-book#110]
Hi @matt-h,

When do you plan to release version 2.0.0 (to the Wordpress plugins directory)?
Changelog is updated, but not released new version.

The current state does not allow me to use translation updates for WooCommerce Address Book (due to ungenerated / untranslated phrases).

**Comment by matt-h** [comment]
Very soon, we just were finishing testing the updated version out on all of the sites that we run the plugin on to make sure everything in the upgrade worked smoothly since there were so many changes.
We are fixing a couple small issues that came up during that testing and then plan to launch 2.0.0 after that.
Should be early next week.

**Comment by Hinyka** [comment]
Thats sounds great.
