### ISSUE TITLE
Bug since upgrading to version 2.1.2 

### ISSUE THREAD

**Issue by jeathree** [hallme/woo-address-book#124]
Everything was working fine in previous version, then I upgraded to 2.1.2.  Now, in checkout, Shipping First Name, Shipping Last Name and Shipping Address 1 are not populated, even though they were filled out during registration and they are in the database.

It weird because Shipping City, State and Zip are populated.

Any ideas?

**Comment by matt-h** [comment]
Those fields populate fine on all of the sites that we run this plugin on.

What was the previous version that you had before 2.1.2 where it worked fine?

Do you have any other plugins that affect the checkout? Did you update any other plugins at the same time as updating to 2.1.2?

**Comment by jeathree** [comment]
I'm not sure what version I was using, it was an old one, from 2-3 years ago.  I switched to a default theme and I was having the same issues.  I'll do some more testing today.

**Comment by matt-h** [comment]
Oh! That does make sense. I thought you were saying in the first message that when you switch address it doesn't populate and not just on page load.

That is a setting whether the Add New Address or an existing address loads by default on checkout. That feature didn't exist yet back in 1.7.5.

If you go to your WooCommerce settings and General and go to the bottom ( This page: `/wp-admin/admin.php?page=wc-settings` ). Then you'll want to make sure "Add New Address as default selection" is unchecked for your shipping address.

![2022-05-23_683x446](https://user-images.githubusercontent.com/664294/169875666-1ecb5551-d483-4d64-93b9-f63e00ad3f60.png)

**Comment by jeathree** [comment]
I looked at that, it was already unchecked.  :(

**Comment by matt-h** [comment]
Maybe try saving it checked and see if it changes the checkout and then change it back just to make sure it upgraded since you are upgrading from such an old version?

**Comment by jeathree** [comment]
I tried checking, saving, then reverting back and it didn't seem to do anything.  I reverted both my production sites using this plugin back to 1.7.5.  I have a local version setup where I will continue to play around when I have time.

**Comment by EnigmaGlenr** [comment]
We have the same issue as stated above.
I dont think the checkbox that you mention actually has an impact on the issue. 

Looking at the plugin code it looks like when the checkout loads its setting the values of shipping_country_o, shipping_state_o, etc... https://github.com/hallme/woo-address-book/blob/10435877363678efcdde7614c32c3327d9b20019/assets/js/scripts.js#L41

Then when the checkout_field_prepop() method runs its checking to see if those values are populated. If they are set its setting the shipping address book to be "add_new".
https://github.com/hallme/woo-address-book/blob/10435877363678efcdde7614c32c3327d9b20019/assets/js/scripts.js#L214

**Comment by EnigmaGlenr** [comment]
As I mentioned in my previous comment I think there is some incorrect logic on line 41 of the scripts.js file.

The comment above line 214 suggests that its for the cart page, however the variables its checking on line 241 are the ones that are set from within the if statement on line 41 where its checking for the form name of checkout.

I think if you update the line 41's if statement to be:
`if($("form.woocommerce-cart-form").length>0 .....`
that should fix the issue?

**Comment by matt-h** [comment]
Thanks @EnigmaGlenr for looking into this. I think you are on the right track with this, but it should be only setting it to `add_new` if the fields found are different from the current default shipping address, so unless they are purposely being changed in the cart then they shouldn't be.

For the line on 41, if that check is failing then it shouldn't be changing it at all. Is the `name` attribute on your checkout form not `checkout` so we should be using `"form.woocommerce-cart-form"` instead of `"form[name=checkout]"`?

My best guess is the field values for one of the values returned isn't matching. Can you check the values in this check: `shipping_country_o !== response.shipping_country || shipping_state_o !== response.shipping_state || shipping_city_o !== response.shipping_city || shipping_postcode_o !== response.shipping_postcode` to see if you do have one that is different?

Adding something like this above the check should show it in your console: `console.log(shipping_country_o, '=', response.shipping_country, shipping_state_o, '=', response.shipping_state, shipping_city_o, '=', response.shipping_city, shipping_postcode_o, '=', response.shipping_postcode);`

If something isn't matching and we can't work around that then we might need to re-think how this check is done.

**Comment by EnigmaGlenr** [comment]
Hi @matt-h,
Thanks for getting back to me. I can check those things but what im not sure about is if those checks should be happening on the checkout page at all?

Looking at the code the code on line 214 it looks like this code should only be getting called on the cart page not on the checkout page as the comment above says "If shipping calculator used on cart page". The code on line 214 (and then the code inside that if statement) is being called on my checkout page not on the cart page. Is that correct?

**Comment by EnigmaGlenr** [comment]
For a bit more context on whats happening here:

1. I load the checkout page and the code on line 41 detects that I have a shipping address and initialises the shipping_xxx_o vairables;
2. I change the shipping address using the dropdown.
3. The code on line 219 is returning true because the original shipping values (saved in the variables in step 1) are different to the ones that have been loaded because of the select option I have selected in step 2.
4. This then sets the shipping address book to the "add_new" value and therefore overriding the selection I have just made.

So essentially I can never select a new shipping address from the Shipping Address Book dropdown as it will always be different to the values stored within the shipping_xxx_o variables.

Hope this helps.

**Comment by matt-h** [comment]
That does help.

> Looking at the code the code on line 214 it looks like this code should only be getting called on the cart page not on the checkout page as the comment above says "If shipping calculator used on cart page". The code on line 214 (and then the code inside that if statement) is being called on my checkout page not on the cart page. Is that correct?
That is not correct. The purpose of this code is if the shipping address was changed during the cart step so that it is different from the values saved in the Default Shipping Address. Then it will preserve those values on the cart and set the address selector to Add New with just the fields from the cart preserved. Assuming that if you changed the address on the cart then you want a new address.

Thanks for the additional context. It sounds like your issue is different than the one [jeathree](https://github.com/jeathree) was talking about, which was a bit of the mixup. It sounds like his is on checkout load and your issue is when you change address with the dropdown.

Under normal circumstances (on our test sites) WooCommerce will load in default values and then the Address Book plugin does the ajax call to get the addresses and at that point it does the comparison of the default address and switches it to Add New right on load. Those values are then cleared out and not used again.

It sounds like your site may not be doing that initial load so the values never get cleared out? So then when you change the address it is running that code. If that is the case then it sounds like we need detection if it is the initial load that is triggering that code or a manual address change (we should probably have that check anyway).

**Comment by matt-h** [comment]
@EnigmaGlenr I just created an update here: https://github.com/hallme/woo-address-book/pull/130

Can you test out the updated [scripts.js](https://github.com/hallme/woo-address-book/blob/fb85b9410d4912e6c4c9dcbaad8bac2622e05332/assets/js/scripts.js) and see if that fixes it for you?

I can't confirm if this fixes it or not since I'm not able to reproduce the issue.

**Comment by matt-h** [comment]
This change is now live in version 2.1.4. Feel free to follow up if it didn't work for you.
