### ISSUE TITLE
Prevent adding address in checkout

### ISSUE THREAD

**Issue by edrisranjbar** [hallme/woo-address-book#127]
**I'm giving clients two options in `checkout` page:**
1. Choose a predefined address from your address book
2. Create a new address here

now it works but the address is being created although user has chosen an old address or entered a new one, which is wrong.
so how can I prevent adding new address in checkout when user chooses predefined address from `address-book`.

**Comment by matt-h** [comment]
I'm not really sure on that. We let WooCommerce handle all of the saving of address on Checkout.

We do override it some here to handle the Add New functionality and a bit more: https://github.com/hallme/woo-address-book/blob/10435877363678efcdde7614c32c3327d9b20019/includes/class-wc-address-book.php#L845

So you can start looking there for customizing it.

Based on this question and your other ones, it sounds like you are trying to customize our plugin to work more like this one: https://woocommerce.com/products/saved-addresses-for-woocommerce/
Which handles addresses a lot differently than we do. I figured I'd mention it since that plugin might align more with the process you are trying to achieve.

**Comment by edrisranjbar** [comment]
I customized a lot of things and its OK, but this is the last piece of issue I'm going through.  and based on your idea, I think I must do a `remove_filter()` to fix this issue.
