### ISSUE TITLE
BUG: overpopulation of checkout fields in database

### ISSUE THREAD

**Issue by andreDane** [hallme/woo-address-book#128]
We have noticed that since version 2.0 (released 3 December 2021) the plugin saves a new billing address (with all fields, e.g. billing2_address_1, billing2_first_name ...) in the DB (usermeta) with each new order, despite the fact that in the WC settings 'Enable billing address book' is not checked.
However, as it is not checked, the user cannot see these additional addresses and the first one will be loaded each time in checkout, even if the data had been changed for subsequent orders: because of this bug, the user will have to fix the billing data each time.

Currently, there are even users with up to 15 additional addresses and counting, so every day the number of users affected by the bug and the size of usermeta table increase by leaps and bounds.

I think the best solution is to replace the data of the base meta (e.g. billing_address_1) with the data of the last meta created (e.g. billing16_address_1), and then remove all additional meta (e.g. billing2_address_1, billing3_address_1, billing4_address_1, billing5_address_1 ... billing16_address_1).

While waiting for a patch, could you point me to a secure code to perform an instant fix?

**Comment by matt-h** [comment]
Hi @andreDane 

Thanks for reporting this. We have confirmed the issue saving to the customer profile if the billing or shipping was disabled during checkout.

We have pushed out version 2.1.3 which fixes this issue so it will no longer save the addresses as new addressees on the profile.

The best way to clean up your data might be to replace the data of the default address with the last entered, although that would be a complicated loop to write to ensure all data copied over accurately.

A quick cleanup would be to just delete the extra meta and then since the issue is resolved then the next time the customer makes a purchase then their address will be saved as default as normal.
You can delete those by just running these 
```
DELETE FROM `wp_usermeta` WHERE `meta_key` LIKE 'billing2_%';
DELETE FROM `wp_usermeta` WHERE `meta_key` LIKE 'billing3_%';
DELETE FROM `wp_usermeta` WHERE `meta_key` LIKE 'billing4_%';
DELETE FROM `wp_usermeta` WHERE `meta_key` LIKE 'billing5_%';
DELETE FROM `wp_usermeta` WHERE `meta_key` LIKE 'billing6_%';
DELETE FROM `wp_usermeta` WHERE `meta_key` LIKE 'billing7_%';
DELETE FROM `wp_usermeta` WHERE `meta_key` LIKE 'billing8_%';
DELETE FROM `wp_usermeta` WHERE `meta_key` LIKE 'billing9_%';
DELETE FROM `wp_usermeta` WHERE `meta_key` LIKE 'billing10_%';
DELETE FROM `wp_usermeta` WHERE `meta_key` LIKE 'billing11_%';
DELETE FROM `wp_usermeta` WHERE `meta_key` LIKE 'billing12_%';
DELETE FROM `wp_usermeta` WHERE `meta_key` LIKE 'billing13_%';
DELETE FROM `wp_usermeta` WHERE `meta_key` LIKE 'billing14_%';
DELETE FROM `wp_usermeta` WHERE `meta_key` LIKE 'billing15_%';
DELETE FROM `wp_usermeta` WHERE `meta_key` LIKE 'billing16_%';
```
_[Disclamer](https://github.com/hallme/woo-address-book/blob/main/LICENSE#L270): You run this at your own risk and we are not liable for any loss of data._

**Comment by andreDane** [comment]
Hi @matt-h ,
thanks for fixing the bug.
However, regarding the additional user meta in the database my problem was that I had users with 85 additional meta in the dev site.
I have solved it with an ad-hoc created plugin that should allow a more efficient cleaning of the database.
I leave the [link](https://github.com/andre-dane-dev/woo-address-book-db-cleaner) with all details here, in case you or anyone else should need it.
If this is a problem, please let me know and I will remove the link.

**Comment by matt-h** [comment]
@andreDane Glad you got it cleaned up.

That is good with me to leave the link in case anyone did have the same issue that you did. A quick read through your plugin code and I don't see any adverse side effects from the method you used to clean it up.
