### ISSUE TITLE
How to set up the language

### ISSUE THREAD

**Issue by Zaiyah** [hallme/woo-address-book#39]
Hey first of all thanks for this great plugin.

I used poedit to translate the pot file.
i named it de_DE. How can i apply the Language file to the plugin?

**Comment by matt-h** [comment]
Hi @Zaiyah 

Thank you for your interest in translating our Plugin. We no longer use the .pot file and have since removed the file from our plugin. We now use the new way of translating WordPress plugins at https://translate.wordpress.org/

Feel free to make and German translations at https://translate.wordpress.org/locale/de/default/wp-plugins/woo-address-book/
