### ISSUE TITLE
Addresses not saving

### ISSUE THREAD

**Issue by dadfuels** [hallme/woo-address-book#43]
When I add and address through the My Account page nothing happens. If I add the address during the checkout process it saves it then but not when I try and create one through My Account/edit-addresses.  I thought it worked before (could be wrong) but it seems to have stopped with the latest woocommerce update.

**Comment by HowdyMcGee** [comment]
I think we're having the same issue.

https://wordpress.org/support/topic/im-not-sure-this-plugin-works/

I can't tell what the room cause is looking at the code. Even with the updated permalink ( noted in the linked thread ) it doesn't seem to have an "Address Name" field added to the shipping form. `$_GET['address-book']` seems to be referenced in a few places - that could possibly be a root cause.

**Comment by matt-h** [comment]
Thank you for the reports @dadfuels and @HowdyMcGee 

This will be fixed in the 1.5.0 release.
